-- Database: moto

-- DROP DATABASE IF EXISTS moto;

CREATE DATABASE moto
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Latvian_Latvia.1257'
    LC_CTYPE = 'Latvian_Latvia.1257'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
    -- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.license;

CREATE TABLE IF NOT EXISTS public.license
(
    "ID" integer NOT NULL,
    license text COLLATE pg_catalog."default",
    "allowed power" integer,
    CONSTRAINT license_pkey PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS public.manufactured;

CREATE TABLE IF NOT EXISTS public.manufactured
(
    "ID" integer NOT NULL,
    manufactured text COLLATE pg_catalog."default",
    countru integer,
    CONSTRAINT manufactured_pkey PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS public."manufactured country";

CREATE TABLE IF NOT EXISTS public."manufactured country"
(
    "ID" integer NOT NULL,
    country text COLLATE pg_catalog."default",
    CONSTRAINT "manufactured country_pkey" PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS public.motorcycle;

CREATE TABLE IF NOT EXISTS public.motorcycle
(
    "ID" integer NOT NULL,
    license integer,
    manufactured integer,
    "Type" integer,
    model text COLLATE pg_catalog."default",
    CONSTRAINT motorcycle_pkey PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS public."motorcycle_Type";

CREATE TABLE IF NOT EXISTS public."motorcycle_Type"
(
    "ID" integer NOT NULL,
    "Type" text COLLATE pg_catalog."default",
    CONSTRAINT "motorcycle_Type_pkey" PRIMARY KEY ("ID")
);

ALTER TABLE IF EXISTS public.manufactured
    ADD CONSTRAINT country FOREIGN KEY (countru)
    REFERENCES public."manufactured country" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_country
    ON public.manufactured(countru);


ALTER TABLE IF EXISTS public.motorcycle
    ADD CONSTRAINT license FOREIGN KEY (license)
    REFERENCES public.license ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_license
    ON public.motorcycle(license);


ALTER TABLE IF EXISTS public.motorcycle
    ADD CONSTRAINT manufactured FOREIGN KEY (manufactured)
    REFERENCES public.manufactured ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_manufactured
    ON public.motorcycle(manufactured);


ALTER TABLE IF EXISTS public.motorcycle
    ADD CONSTRAINT type FOREIGN KEY ("Type")
    REFERENCES public."motorcycle_Type" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_type
    ON public.motorcycle("Type");

END;